### ISSUE TITLE
Allow developers to add a new employee training instance

### ISSUE THREAD

**Issue by kellymorin** [raving-remoras/Bangazon-React#15]
- [ ]  From the main employee training overview page, if the user selects the add employee training option, they will be taken to a form
- [ ]   The form will allow the user to select employees that are not currently attending that training session, or create a new employee instance
- [ ]   New employee instance would display the form in ticket #21 
- [ ]   New department instance would display the form in ticket #19 
- [ ]   The form will also allow the user to select training sessions that have not yet happened, or create a new training instance 
- [ ]   New training instance would display the form in ticket #12
