### ISSUE TITLE
A User can Edit an Order

### ISSUE THREAD

**Issue by racheldaniel** [raving-remoras/Bangazon-React#36]
- [x] When the user clicks on an individual order, they will be taken to a detail page, which is structured as a pre-populated edit form
- [x] Along with the edit form, the user should be able to see all details for products included in that order (link to the product detail page ticket #24)
- [x]  On the edit order form, a user has the option to select from pre-existing customers and payment types
- [ ] Once the user selects a customer or payment type, they have the affordance to edit that entity (edit forms #39 and #30)
- [ ] A user can also add a new payment type and/or customer from the add order page (add forms from #38 and #29)
- [x] The user has the option to "save"-- which routes back to order list

**Comment by kellymorin** [comment]
Completed, team decided to not allow for adding or editing other entities from the edit form.
